version: "3.98"
services:
  test-server:
    image: web5-component:latest
    ports:
      - 8080
  test-client:
    build:
      context: .
    command:
      [
        "/web5-components-tests",
        "--no-start",
        "--server",
        "http://test-server:8080",
      ]
    depends_on:
      - test-server
